### ISSUE TITLE
Some errors were encountered when parsing the FUNDING.yml file

### ISSUE THREAD

**Issue by ismaail** [Stokoe0990/wikivel#10]
I get this error when I click ib "Sponsor" button.

![Image](https://i.ibb.co/KXwp7Sg/Screenshot-2019-10-14-Replace-sql-WHERE-inside-foreach-loop-by-ismaail-Pull-Request-9-Stokoe0990-wikivel.png)

**Comment by Stokoe0990** [comment]
Fixed, thankyou! :)
