### ISSUE TITLE
Favorites page is broken

### ISSUE THREAD

**Issue by Jhnbrn90** [Stokoe0990/wikivel#6]
Currently, when running the project locally, I favorited the "Batman" wiki from the example seed data and get the following error when navigating to the '/favorites' endpoint. 

<img width="1251" alt="Schermafbeelding 2019-10-14 om 17 27 17" src="https://user-images.githubusercontent.com/24190396/66763294-e460a980-eea7-11e9-8110-0ae53cfef802.png">

**Comment by Stokoe0990** [comment]
Likely an aftereffect of a fix I made. Cheers for the PR and fixing the horrid "fix" I made.

I've merged the [PR](https://github.com/Stokoe0990/wikivel/pull/7/commits/3d57e8a8d3271e01e58637f12e5ccd2d955601cd).
