### ISSUE TITLE
Differences in license

### ISSUE THREAD

**Issue by ssddanbrown** [Stokoe0990/wikivel#8]
License details in readme are as follows:

> Do what you want. But credit me. That's all I ask!

Whereas [license file](https://github.com/Stokoe0990/wikivel/blob/master/LICENSE) is GPLv3. Might cause some confusion. 

---

Congrats on the project and good luck! Found this via Reddit.  Will be interesting to see another Laravel based wiki about. Feel free to jump into the [BookStack discord](https://discord.gg/ztkBqR2) if you ever have any questions.

**Comment by Stokoe0990** [comment]
Thanks man! Will fix that now. Cheers.

Ooo I will do. Thanks again.
